### ISSUE TITLE
Error Java

### ISSUE THREAD

**Issue by ofitecno** [mcgitty/install-alfresco-6x.sh#1]
First congratulations, very good job.
I installed Alfresco 6.2 with your script but I have a problem in Catalina.out (tomcat) and not start (Ubuntu 18.04):

Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I have installed Oracle JDK 11.0.7 and my JAVA_HOME is /usr/lib/jvm/jdk-11.0.7. I downloaded the last script version 24-04-2020 but when I run alfresco.sh or catalina,sh the server not starter.

I have tried to modify setenv.sh and run but I don't know if it's good practise deletion of -XX:+UseConcMarkSweepGC -XX:+UseParNewGC. Is it necesary other change???
Original:
JAVA_OPTS="-XX:+DisableExplicitGC -Djava.awt.headless=true -XX:ReservedCodeCacheSize=128m $JAVA_OPTS"
JAVA_OPTS="-Xms512M -Xmx8192M -Djgroups.bind_addr=127.0.0.1 $JAVA_OPTS -XX:+UseConcMarkSweepGC -XX:+UseParNewGC"
export JAVA_OPTS

Modified: 
JAVA_OPTS="-XX:+DisableExplicitGC -Djava.awt.headless=true -XX:ReservedCodeCacheSize=128m $JAVA_OPTS"
JAVA_OPTS="-Xms512M -Xmx8192M -Djgroups.bind_addr=127.0.0.1 $JAVA_OPTS"
export JAVA_OPTS

With Setenv modified run...

**Comment by mcgitty** [comment]
My last commit (6c25d46d) tries to detect JVM version. Option 'UseParNewGC' is added only if JVM is < 1.9. Is it possible that when you run the bash script, JAVA_HOME was pointing to 1.8?
