### ISSUE TITLE
Granting privileges to alfresco users doesn't work in recent Mysql versions

### ISSUE THREAD

**Issue by Stonica** [mcgitty/install-alfresco-6x.sh#3]
The following sql script:

`GRANT ALL PRIVILEGES ON alf620ce.* to 'alfresco'@'localhost' identified by 'alfresco' with grant option;`

must be changed to:

`GRANT ALL PRIVILEGES ON alf620ce.* TO 'alfresco'@'localhost' WITH GRANT OPTION;`

to work in recent versions of Mysql, also I think the full mysql script must be like below:

```
$ mysql -u root

create schema alf620ce default character set utf8;

CREATE USER 'alfresco'@'localhost' IDENTIFIED BY 'alfresco';

GRANT ALL PRIVILEGES ON alf620ce.* TO 'alfresco'@'localhost' WITH GRANT OPTION;
```

**Comment by mcgitty** [comment]
What version of MySQL must you create the user/password first then grant privileges?

**Comment by mcgitty** [comment]
I see. Oracle deprecated `[auth_option]` from the TO clause of GRANT in version 5.7 and removed it completely in version 8:

[MySQL 5.7 GRANT](https://dev.mysql.com/doc/refman/5.7/en/grant.html#grant-accounts-passwords)
[MySQL 8.0 GRANT](https://dev.mysql.com/doc/refman/8.0/en/grant.html#grant-accounts)

**Comment by mcgitty** [comment]
PR5 updated README with separate CREATE USER command.
